Fixed pagination for Genres, completed Developer Mod & Cont
YousefAbdelnour/vgames-api pull request #25
Opened 2024-09-27 13:32 UTC by RoLajoie

Fixed pagination for Genres, added Controller, Model and Pagination for Developer resource

2024-09-29 22:45 UTC, cr4zy30 commented
Update collection and singleton controllers with new validation methods. View handleGetGames() and handleGetGameById()

2024-09-30 21:22 UTC, YousefAbdelnour requested changes
Follow Dennis' helpers function. good to go otherwise though

2024-10-02 12:54 UTC, cr4zy30 requested changes
Everything looks great, just some small changes:

return $this->renderJson($response, [
"data" => $developer,
], StatusCodeInterface::STATUS_OK);

Some of our current code doesn't follow this practice yet, but we agreed to name the key as the name of the collection being returned, in this case, instead of being "data", it would be "developer" for singletons, and "developers" for collections. When it's a sub-collection, let's say /developer/{developer_id}/games, it would also be "developer" with a list of "games" inside the object.

Also, you can keep it this way because it doesn't change anything, but it's not mandatory to specify the status code, it's 200 OK by default.

👍💯

2024-10-02 14:15 UTC, cr4zy30 approved these changes
"data" => $developers

But that's fine you can change it next PR

2024-10-02 14:16 UTC, YousefAbdelnour requested changes

2024-10-02 14:16 UTC, YousefAbdelnour commented on app/src/Controllers/DeveloperController.php
> +            "data" => $developer,
"data" supposed to be "developer" or something like that. follow naming convention

2024-10-02 14:16 UTC, YousefAbdelnour commented on app/src/Controllers/DeveloperController.php
> +            "data" => $developers
"data" supposed to be "developer" or something like that. follow naming convention

2024-10-02 14:17 UTC, YousefAbdelnour commented
If you want to merge and then change that for the next PR. fine by me

Approval up to you @cr4zy30 

(edit) sorry didn' see your approval Denis

2024-10-02 14:19 UTC, merged