Reviews sub-collection for games
YousefAbdelnour/vgames-api pull request #31
Opened 2024-09-30 18:56 UTC by cr4zy30

2024-09-30 19:00 UTC, YousefAbdelnour approved these changes
awesome

2024-09-30 21:21 UTC, YousefAbdelnour requested changes
same thing. follow my countries games PR for the same format

2024-10-01 13:16 UTC, YousefAbdelnour requested changes
do those changes ples

2024-10-01 13:16 UTC, YousefAbdelnour commented on app/src/Models/GameModel.php
> +        $sql = "SELECT * FROM review WHERE game_id = :game_id";
Get genre dev and country info along with review and game

2024-10-02 17:27 UTC, cr4zy30 commented
Here's what the response looks like after including the developer, country, and genre
![image](https://github.com/user-attachments/assets/07b01d84-821b-48a6-8b16-e6aa7f8fbf0d)

2024-10-05 13:40 UTC, YousefAbdelnour approved these changes
LGTM👌

2024-10-05 13:45 UTC, YousefAbdelnour commented
We have merge conflict. don't know how to solve it. Up to you @cr4zy30

2024-10-05 14:15 UTC, merged