Platforms sub-collection for games
YousefAbdelnour/vgames-api pull request #32
Opened 2024-09-30 19:53 UTC by cr4zy30

2024-09-30 21:20 UTC, YousefAbdelnour requested changes
Follow the logic in my PR for countries/name/games. should have specific format and different tables than a big table with repeated field names

2024-10-01 13:17 UTC, YousefAbdelnour requested changes
same thing. check comment on code

2024-10-01 13:17 UTC, YousefAbdelnour commented on app/src/Models/GameModel.php
> +        return (array) $this->paginate($sql, ["game_id" => $game_id]);
genre country dev info to be added

2024-10-02 17:43 UTC, cr4zy30 commented
Updated response with information about **country**, **developer**, and **genre**:
![image](https://github.com/user-attachments/assets/55a670bc-1d28-481a-a5e2-d2fb781ed1e7)

2024-10-05 13:41 UTC, YousefAbdelnour approved these changes
Nice.

2024-10-05 13:41 UTC, merged