DELETE games
YousefAbdelnour/vgames-api pull request #63
Opened 2024-10-25 18:17 UTC by cr4zy30

For DELETE requests, ID is passed inside the body with the 'id' field as a string or integer.
![image](https://github.com/user-attachments/assets/cbd8c166-3857-40fc-9538-42324f1df87b) 
![image](https://github.com/user-attachments/assets/221047e0-7737-4d4d-bd1d-0923d22e16e6)

If the 'id' field is not included in the body: 
![image](https://github.com/user-attachments/assets/249e123e-33b7-4167-b189-f5b535bb5d47)

If the id has letters:
![image](https://github.com/user-attachments/assets/5226472d-de7f-471d-b49b-178a3b38a147)

If the id doesn't exist:
![image](https://github.com/user-attachments/assets/265b8a6a-e436-4031-87d9-e2ab8d68da9c)

Response upon successful deletion: (200 OK) (Deleted object is returned, in this case deleted_game)
![image](https://github.com/user-attachments/assets/2e178182-ab9e-44cb-a1eb-3a145124d3ee)

2024-10-26 13:25 UTC, YousefAbdelnour approved these changes
Looks great!

2024-10-26 13:27 UTC, YousefAbdelnour commented
@cr4zy30 i tried to resolve the conflict. read the routes file and the model file for this pr and if there is anything wrong with your changes change it. I just appended everything

2024-10-28 15:04 UTC, YousefAbdelnour requested changes

2024-10-28 15:04 UTC, YousefAbdelnour commented on app/src/Services/GamesService.php
> +        } else if (!$this->game_model->isValidGameId($body['id'])) {
wouldnt this not check the id if its valid or not because of the else if?

for example if we pass an id, the validator will check for the rule which makes sure that it is an int and existing, but then it will not check if its existing in the database cuz that call is in the else if and not in a separate if statement?

2024-10-28 15:28 UTC, cr4zy30 commented on app/src/Services/GamesService.php
> +        } else if (!$this->game_model->isValidGameId($body['id'])) {
It's a bit tricky, but the logic here is that you only check if the ID exists if it's validated by Valitron's rules. 

Let's say the given ID is wrong according to Valitron's rules. In this case, it will enter the first if block and return errors such as "ID is required" or "ID must be an integer." It won't check if the ID exists.

If the given ID is valid according to Valitron, it won't enter the first if block, it will enter the second one. 
That's also why I don't check if $body['id'] is set before accessing it because if it wasn't, the Valitron rules would've failed and it would've entered the first if block. (because of the 'required' rule)

I did things differently in POST in PUT. I check for both conditions, so the user gets all the error messages right away (the ones from Valitron such as required, integer, min, max, length, and the ones from FK validation such as ID doesn't exist). 

Let's say the given ID is "test" for DELETE /games, here's what the client receives if we send back all errors:
"ID should be an integer, string given"
"Could not find game with ID [test]"

In this case, I think it makes more sense to send the first error only (for DELETE operations). What do you think?

2024-10-28 15:32 UTC, YousefAbdelnour approved these changes

2024-10-29 12:11 UTC, merged